version: '3.4'

services:
  oram:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/isgx
    volumes:
      - ./oramsgx:/usr/src/oram/oramsgx
      - ./:/usr/src/oram/
      - aesmd-socket:/var/run/aesmd
    environment:
      LD_LIBRARY_PATH: /opt/intel/sgx-aesm-service/aesm
    command: bash
volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"
